version: '3'

services:

  app:
    build: .
    command: ['./start.sh', $PORT]
    depends_on:
    - postgres
    env_file:
    - .env
    ports:
      - "1337:1337"

  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
